app: mai
org: beemer

service:
  name: mai

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello
  ask:
    handler: src/handler.ask
    events:
      - http:
          method: get
          path: ask
