name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
          npm test
        env:
          CI: true
      - name: install and configure serverless
        run: |
          npm i -g serverless
          sls config credentials --provider aws --key ${AWS_SECRET_KEY} --secret ${AWS_SECRET_TOKEN} --overwrite
      - name: prestart and deploy
        run: |
          npm run prestart:prod
          sls deploy
        env:
          AWS_SECRET_KEY: ${secret.AWS_SECRET_KEY}
          AWS_SECRET_TOKEN: ${secret.AWS_SECRET_TOKEN}
